name       : g810-led
version    : 0.2.9
release    : 3
source     :
    - https://github.com/MatMoul/g810-led/archive/v0.2.9.tar.gz : 1a65631fb9d4769529f18a5e927473833e3104b448a0f6da82b437ba4a062092
license    : GPL-3.0-only
component  : system.utils
summary    : Linux led controller for Logitech G213, G410, G413, G610, G810, G910 and GPRO Keyboards
description: |
    Linux led controller for Logitech G213, G410, G413, G610, G810, G910 and GPRO Keyboards
builddeps  :
    - pkgconfig(hidapi-libusb)
setup      : |
    sed -i "s|/etc/udev|%libdir%/udev|g" makefile
    sed -i "s|etc|usr/share|g" makefile systemd/g810-led-reboot.service udev/g810-led.rules
build      : |
    %make
install    : |
    %make setup DESTDIR=$installdir libdir=%libdir% SYSTEMDDIR=%libdir%/systemd
